import { Request, Response } from 'express';
import { CityIntersectionNode, Direction, LightState } from '../types';
import { trafficEngine } from '../services/trafficEngine';
import { emergencyManager } from '../services/emergencyManager';

export const getCityIntersections = (req: Request, res: Response) => {
  const liveTelemetry = trafficEngine.getLiveTelemetry();
  const activeEmergency = emergencyManager.getActiveEmergency();

  const intersections: CityIntersectionNode[] = [
    {
      id: 'J001',
      name: 'Connaught Place Central Circle',
      code: 'CP-01',
      locationName: 'Radial Arterial Central Ring',
      x: 50,
      y: 42,
      lat: 28.6315,
      lng: 77.2167,
      activeDirection: liveTelemetry.activeDirection,
      currentSignal: liveTelemetry.roads[liveTelemetry.activeDirection].currentSignal,
      vehicleCount: liveTelemetry.totalVehicleCount,
      congestionLevel: liveTelemetry.congestionIndex > 70 ? 'HIGH' : liveTelemetry.congestionIndex > 40 ? 'MEDIUM' : 'LOW',
      connectedNodeIds: ['J002', 'J004', 'J005'],
      hasEmergency: Boolean(activeEmergency),
      efficiencyRating: '92.4%',
    },
    {
      id: 'J002',
      name: 'AIIMS Ring Road Flyover Intercept',
      code: 'AIIMS-02',
      locationName: 'Sri Aurobindo Marg & Ring Road',
      x: 48,
      y: 72,
      lat: 28.5672,
      lng: 77.2100,
      activeDirection: 'NORTH',
      currentSignal: 'GREEN',
      vehicleCount: 38,
      congestionLevel: 'HIGH',
      connectedNodeIds: ['J001', 'J006', 'J003'],
      hasEmergency: activeEmergency?.junctionId === 'J002',
      efficiencyRating: '88.1%',
    },
    {
      id: 'J003',
      name: 'Cyber City Expressway Plaza',
      code: 'CYB-03',
      locationName: 'NH-48 DLF Phase 2 Corridor',
      x: 22,
      y: 80,
      lat: 28.4900,
      lng: 77.0900,
      activeDirection: 'WEST',
      currentSignal: 'GREEN',
      vehicleCount: 52,
      congestionLevel: 'CRITICAL',
      connectedNodeIds: ['J002', 'J001'],
      hasEmergency: false,
      efficiencyRating: '84.6%',
    },
    {
      id: 'J004',
      name: 'Sector 62 Electronic City Hub',
      code: 'SEC62-04',
      locationName: 'Noida Model Town Crossing',
      x: 82,
      y: 45,
      lat: 28.6250,
      lng: 77.3650,
      activeDirection: 'EAST',
      currentSignal: 'RED',
      vehicleCount: 29,
      congestionLevel: 'MEDIUM',
      connectedNodeIds: ['J001', 'J007'],
      hasEmergency: false,
      efficiencyRating: '90.2%',
    },
    {
      id: 'J005',
      name: 'India Gate C-Hexagon Circle',
      code: 'INDG-05',
      locationName: 'Kartavya Path Arterial Ring',
      x: 58,
      y: 52,
      lat: 28.6129,
      lng: 77.2295,
      activeDirection: 'SOUTH',
      currentSignal: 'GREEN',
      vehicleCount: 24,
      congestionLevel: 'LOW',
      connectedNodeIds: ['J001', 'J006'],
      hasEmergency: false,
      efficiencyRating: '95.8%',
    },
    {
      id: 'J006',
      name: 'Lajpat Nagar Flyover Junction',
      code: 'LJP-06',
      locationName: 'Feroze Gandhi Marg & Inner Ring',
      x: 62,
      y: 68,
      lat: 28.5700,
      lng: 77.2400,
      activeDirection: 'WEST',
      currentSignal: 'RED',
      vehicleCount: 31,
      congestionLevel: 'MEDIUM',
      connectedNodeIds: ['J005', 'J002', 'J007'],
      hasEmergency: false,
      efficiencyRating: '89.5%',
    },
    {
      id: 'J007',
      name: 'Noida Expressway Mahamaya Gateway',
      code: 'NOIDA-07',
      locationName: 'Sector 44 Yamuna Bank Bypass',
      x: 85,
      y: 75,
      lat: 28.5480,
      lng: 77.3300,
      activeDirection: 'EAST',
      currentSignal: 'GREEN',
      vehicleCount: 45,
      congestionLevel: 'HIGH',
      connectedNodeIds: ['J004', 'J006'],
      hasEmergency: false,
      efficiencyRating: '91.0%',
    },
  ];

  res.json({
    success: true,
    data: {
      city: 'Delhi-NCR Metropolitan Smart Corridor',
      totalActiveIntersections: intersections.length,
      connectedCorridorsCount: 9,
      networkCongestionAverage: '48.6%',
      intersections,
    },
  });
};

export const getCityCorridorRoutes = (req: Request, res: Response) => {
  const routes = [
    {
      id: 'CORR-01',
      name: 'East-West Arterial Expressway',
      from: 'J003',
      to: 'J004',
      via: ['J002', 'J001'],
      totalDistanceKm: 28.4,
      synchronizedGreenWave: true,
      averageSpeedKmh: 54,
    },
    {
      id: 'CORR-02',
      name: 'North-South Heritage & Medical Corridor',
      from: 'J001',
      to: 'J002',
      via: ['J005', 'J006'],
      totalDistanceKm: 14.2,
      synchronizedGreenWave: true,
      averageSpeedKmh: 48,
    },
    {
      id: 'CORR-03',
      name: 'Trans-Yamuna Expressway Link',
      from: 'J004',
      to: 'J007',
      via: [],
      totalDistanceKm: 10.8,
      synchronizedGreenWave: false,
      averageSpeedKmh: 62,
    },
  ];

  res.json({ success: true, data: routes });
};
